//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScrach2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> MovieID { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual User User { get; set; }
    }
}
