//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScrach2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class amugh786_aziz_dbEntities : DbContext
    {
        public amugh786_aziz_dbEntities()
            : base("name=amugh786_aziz_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatelogComponent> CatelogComponents { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<MovieLinkGenre> MovieLinkGenres { get; set; }
        public virtual DbSet<MovieLinkPlatform> MovieLinkPlatforms { get; set; }
        public virtual DbSet<Plateform> Plateforms { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
    }
}
